Changes for jira PUBSTWO-1669 (Query by doi)
usgs/pubs-services pull request #29
Opened 2019-09-04 21:04 UTC by orosz-usgs

Refactored MpPublicationMvcService, PwPublicationMvcService and PwPublicationRssMvcService to use
a pojo object for the query parameter in the method for a http GET
  Update MvcService.buildFilters to just take the pojo filtering class as the single argument
  Moved the current functionality of the "doi" parameter to a new "hasDoi" parameter
  Updated the functionality of the "doi" parameter match on the doi string value.
  Updated MvcServiceTest and PublicationDaoIT

2019-09-05 16:09 UTC, dsteinich requested changes

2019-09-05 16:09 UTC, dsteinich commented on src/main/java/gov/usgs/cida/pubs/webservice/GlobalDefaultExceptionHandler.java
> +			errorMess = errorMess + sep + prefix + mess;
Would it be better to use a StringBuilder here (rather than concatenating).

2019-09-05 16:09 UTC, dsteinich commented on src/main/java/gov/usgs/cida/pubs/webservice/mp/MpPublicationMvcService.java
> +	@RequestMapping(method=RequestMethod.GET)
What is the reasoning behind using both `@GetMapping` and `@RequestMapping`?

2019-09-05 16:09 UTC, dsteinich commented on src/main/java/gov/usgs/cida/pubs/webservice/mp/MpPublicationMvcService.java
> +		System.out.println("DEBUG: filetr-= " + filterParams);
Please use LOG.debug rather than System.out.println

2019-09-05 16:09 UTC, dsteinich commented on src/main/java/gov/usgs/cida/pubs/webservice/pw/PwPublicationMvcService.java
> +	@RequestMapping(method=RequestMethod.GET)
Same question on using both annotations.

2019-09-05 16:09 UTC, dsteinich commented on src/main/java/gov/usgs/cida/pubs/webservice/pw/PwPublicationRssMvcService.java
> +	@RequestMapping(method=RequestMethod.GET)
Same question on using both annotations.

2019-09-05 16:09 UTC, dsteinich commented on src/main/resources/mybatis/mappers/publication.xml
> +            <if test="doi != null and doi.length > 0">
the `(` and `)` could be moved to the `foreach` - `<foreach item="d" collection="doi" open="(" separator="or" close=")">`
Might even be able to move the `and` into the `open`

2019-09-05 16:09 UTC, dsteinich commented on src/test/java/gov/usgs/cida/pubs/dao/PublicationDaoIT.java
> +		filters.put(PublicationDao.DOI, new String[]{"DOI-123"});
Can you add a second doi here to show that the foreach is set up correctly? (The separator is valid.)

It also looks like the getByMapTest() in this class hasn't been truly kept up to date. There should be a separate test showing that specifying just DOI values returns the correct publications and one that shows specifying just the hasDoi returns the correct publications.  (Might also be time to split it into individual test.)

2019-09-05 16:42 UTC, orosz-usgs commented on src/main/java/gov/usgs/cida/pubs/webservice/mp/MpPublicationMvcService.java
> +	@RequestMapping(method=RequestMethod.GET)
it was one of those that I could have swore it was needed. Do not know what was wrong
when I tried it earlier. Yes, the second annotation is not needed

2019-09-06 19:26 UTC, dsteinich requested changes

2019-09-06 19:26 UTC, dsteinich commented on src/main/resources/mybatis/mappers/publication.xml
> +            <if test="doi != null and doi.length > 0">
I'd really like to see the parenthesis moved to the open and close.

2019-09-09 14:10 UTC, merged